export const ICONS = {
  star: {
    label: "Star",
    path: "M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 22 12 18.27 5.82 22 7 14.14l-5-4.87 6.91-1.01L12 2z",
    fill: "#d97706",
  },
  medal: {
    label: "Medal",
    path: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z",
    fill: "#b45309",
  },
  checkmark: {
    label: "Checkmark",
    path: "M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z",
    fill: "#059669",
  },
  seal: {
    label: "Seal",
    path: "M12 1l2.93 5.94L21 8.24l-4.35 4.24 1.03 5.99L12 15.4l-5.68 2.99 1.03-5.99L3 8.16l6.07-.22L12 1z",
    fill: "#7c3aed",
  },
} as const;

export const RIBBONS = {
  ribbon1: {
    label: "Ribbon",
    path: "M2 20h20l-4-8 4-8H2l4 8-4 8z",
    fill: "#1e3a5f",
  },
  ribbon2: {
    label: "Banner",
    path: "M1 5h22v14H1V5zm2 2v10h18V7H3z M0 8l3-3v6L0 8z M24 8l-3-3v6l3-3z",
    fill: "#0d4a6b",
  },
} as const;

export const BUILDER_ELEMENT_ICONS = [
  { label: "Badge 1", url: "/ICONS_updated/1.svg" },
  { label: "Badge 2", url: "/ICONS_updated/2.svg" },
  { label: "Badge 3", url: "/ICONS_updated/3.svg" },
  { label: "Badge 4", url: "/ICONS_updated/4.svg" },
  { label: "Badge 5", url: "/ICONS_updated/5.svg" },
  { label: "Badge 6", url: "/ICONS_updated/6.svg" },
  { label: "Badge 7", url: "/ICONS_updated/7.svg" },
  { label: "Badge 8", url: "/ICONS_updated/8.svg" },
  { label: "Badge 9", url: "/ICONS_updated/9.svg" },
  { label: "Badge 10", url: "/ICONS_updated/10.svg" },
  { label: "Badge 11", url: "/ICONS_updated/11.svg" },
  { label: "Badge 12", url: "/ICONS_updated/12.svg" },
  { label: "Badge 13", url: "/ICONS_updated/13.svg" },
  { label: "Trophy 14", url: "/ICONS_updated/trophy 14.svg" },
  { label: "Trophy 15", url: "/ICONS_updated/trophy 15.svg" },
  { label: "Badge 16", url: "/ICONS_updated/16.svg" },
  { label: "Badge 17", url: "/ICONS_updated/17.svg" },
  { label: "Badge 18", url: "/ICONS_updated/18.svg" },
  { label: "Diamond 19", url: "/ICONS_updated/19 daimond.svg" },
  { label: "Badge 20", url: "/ICONS_updated/20.svg" },
  { label: "Badge 21", url: "/ICONS_updated/21.svg" },
  { label: "Badge 22", url: "/ICONS_updated/22.svg" },
  { label: "Badge 23", url: "/ICONS_updated/23.svg" },
  { label: "Badge 24", url: "/ICONS_updated/24.svg" },
  { label: "Badge 25", url: "/ICONS_updated/25.svg" },
  { label: "Badge 26", url: "/ICONS_updated/26.svg" },
  { label: "Badge 27", url: "/ICONS_updated/27.svg" },
  { label: "Badge 28", url: "/ICONS_updated/28.svg" },
  { label: "Badge 29", url: "/ICONS_updated/29.svg" },
  { label: "Badge 30", url: "/ICONS_updated/30.svg" },
  { label: "Badge 31", url: "/ICONS_updated/31.svg" },
  { label: "Badge 32", url: "/ICONS_updated/32.svg" },
  { label: "Badge 33", url: "/ICONS_updated/33.svg" },
  { label: "Badge 34", url: "/ICONS_updated/34.svg" },
];

export const BUILDER_ELEMENT_SHAPES = [
  { label: "Shape 1", url: "/Shapes_updated/1.svg" },
  { label: "Shape 2", url: "/Shapes_updated/2.svg" },
  { label: "Shape 3", url: "/Shapes_updated/3.svg" },
  { label: "Shape 4", url: "/Shapes_updated/4.svg" },
  { label: "Shape 5", url: "/Shapes_updated/5.svg" },
  { label: "Shape 6", url: "/Shapes_updated/6.svg" },
  { label: "Shape 7", url: "/Shapes_updated/7.svg" },
  { label: "Shape 8", url: "/Shapes_updated/8.svg" },
  { label: "Shape 9", url: "/Shapes_updated/9.svg" },
  { label: "Shape 10", url: "/Shapes_updated/10.svg" },
  { label: "Shape 11", url: "/Shapes_updated/11.svg" },
  { label: "Shape 12", url: "/Shapes_updated/12.svg" },
];

export const BUILDER_ELEMENT_RIBBONS = [
  { label: "Ribbon 1", url: "/Ribons_updated/1.svg" },
  { label: "Ribbon 2", url: "/Ribons_updated/2.svg" },
  { label: "Ribbon 3", url: "/Ribons_updated/3.svg" },
  { label: "Ribbon 4", url: "/Ribons_updated/4.svg" },
  { label: "Ribbon 5", url: "/Ribons_updated/5.svg" },
  { label: "Ribbon 6", url: "/Ribons_updated/6.svg" },
  { label: "Ribbon 7", url: "/Ribons_updated/7.svg" },
  { label: "Ribbon 8", url: "/Ribons_updated/8.svg" },
  { label: "Ribbon 9", url: "/Ribons_updated/9.svg" },
  { label: "Ribbon 10", url: "/Ribons_updated/10.svg" },
  { label: "Ribbon 11", url: "/Ribons_updated/11.svg" },
  { label: "Ribbon 12", url: "/Ribons_updated/12.svg" },
];

export const BUILDER_ELEMENT_BASES = [
  { label: "Base 1", url: "/Bases_updated/1.svg" },
  { label: "Base 2", url: "/Bases_updated/2.svg" },
  { label: "Base 3", url: "/Bases_updated/3.svg" },
  { label: "Base 4", url: "/Bases_updated/4.svg" },
  { label: "Base 5", url: "/Bases_updated/5.svg" },
  { label: "Base 6", url: "/Bases_updated/6.svg" },
  { label: "Base 7", url: "/Bases_updated/7.svg" },
  { label: "Base 8", url: "/Bases_updated/8.svg" },
  { label: "Base 9", url: "/Bases_updated/9.svg" },
  { label: "Base 10", url: "/Bases_updated/10.svg" },
  { label: "Base 11", url: "/Bases_updated/11.svg" },
  { label: "Base 12", url: "/Bases_updated/12.svg" },
  { label: "Base 13", url: "/Bases_updated/13.svg" },
  { label: "Base 14", url: "/Bases_updated/14.svg" },
  { label: "Base 15", url: "/Bases_updated/15.svg" },
  { label: "Base 16", url: "/Bases_updated/16.svg" },
  { label: "Base 17", url: "/Bases_updated/17.svg" },
  { label: "Base 18", url: "/Bases_updated/18.svg" },
  { label: "Base 19", url: "/Bases_updated/19.svg" },
  { label: "Base A", url: "/Bases_updated/A.svg" },
  { label: "Base D", url: "/Bases_updated/D.svg" },
  { label: "Base F", url: "/Bases_updated/F.svg" },
  { label: "Base G", url: "/Bases_updated/G.svg" },
  { label: "Base H", url: "/Bases_updated/H.svg" },
  { label: "Base I", url: "/Bases_updated/I.svg" },
  { label: "Base J", url: "/Bases_updated/J.svg" },
  { label: "Base L", url: "/Bases_updated/L.svg" },
  { label: "Base M", url: "/Bases_updated/M.svg" },
  { label: "Base N", url: "/Bases_updated/N.svg" },
  { label: "Base O", url: "/Bases_updated/O.svg" },
  { label: "Base P", url: "/Bases_updated/P.svg" },
  { label: "Base Q", url: "/Bases_updated/Q.svg" },
  { label: "Base R", url: "/Bases_updated/R.svg" },
  { label: "Base S", url: "/Bases_updated/S.svg" },
  { label: "Base U", url: "/Bases_updated/U.svg" },
  { label: "Base b", url: "/Bases_updated/b.svg" },
  { label: "Base c", url: "/Bases_updated/c.svg" },
  { label: "Base e", url: "/Bases_updated/e.svg" },
  { label: "Base k", url: "/Bases_updated/k.svg" },
  { label: "Base t", url: "/Bases_updated/t.svg" },
];

export type IconKey = keyof typeof ICONS;
export type RibbonKey = keyof typeof RIBBONS;
